[Issue #85] Adding OpenBLAS as external lib.
ibayer/fastFM-core pull request #19
Opened 2017-01-23 20:05 UTC by iramykytyn

Look at https://github.com/ibayer/fastFM/issues/85. OpenBLAS is needed for linking with fastfm.a.

2017-01-24 12:41 UTC, ibayer commented
Please link against OpenBlas in all Makefiles. Otherwise the tests can't tell us if the library works fine with the newly added OpenBlas files.

* https://github.com/ibayer/fastFM-core/blob/master/demo/Makefile#L5
* https://github.com/ibayer/fastFM-core/blob/master/src/Makefile#L3
* https://github.com/ibayer/fastFM-core/blob/master/src/tests/Makefile#L10

2017-01-25 20:05 UTC, ibayer requested changes
Please remove as many includes as possible from the `demo/Makefile`. Some of them should definitely be statically compiled into `fastfm`. If this doesn't work here it also won't work if we call the lib from python.

2017-01-25 20:05 UTC, ibayer commented on demo/Makefile
> +INCLUDE = -I../include -L../bin -I../externals/CXSparse/Include -I../externals/OpenBLAS
Do we really need `-I../externals/OpenBLAS`?

2017-01-25 20:05 UTC, ibayer commented on demo/Makefile
> +LDLIBS = -L../bin -lfastfm -L../externals/CXSparse/Lib -lcxsparse -L../externals/OpenBLAS -lopenblas -lpthread -lm
`-L../externals/CXSparse/Lib -lcxsparse -L../externals/OpenBLAS -lopenblas -lpthread`
This  libraries should all be included in `-lfastfm`.

2017-01-25 20:31 UTC, ibayer commented on demo/Makefile
> +LDLIBS = -L../bin -lfastfm -lopenblas -lpthread -lm
why do we stil need `-lopenblas -lpthread `?

2017-01-25 20:31 UTC, ibayer commented on src/Makefile
> +LDLIBS = -L../bin -lfastfm -lpthread -lm
The lib is only used in `demo/Makefile`. I think this change should be reset.

2017-01-25 20:31 UTC, ibayer commented on src/tests/Makefile
same as above

2017-01-25 22:37 UTC, iramykytyn commented on src/tests/Makefile
Here it is used for linking with some blas functions which lib consists.

2017-01-25 22:42 UTC, ibayer commented on src/tests/Makefile
Yes I understand, but it's still better to link against openblas directly here.

2017-01-25 22:44 UTC, ibayer commented on src/Makefile
> +LDLIBS = -L../bin -lfastfm -lpthread -lm
Same as below, please link against openblas instead of  `-lfastfm`.

2017-01-25 22:47 UTC, iramykytyn commented on src/Makefile
> +LDLIBS = -L../bin -lfastfm -lpthread -lm
lib is needed here for proper linking in cli target

2017-01-25 22:52 UTC, iramykytyn commented on src/tests/Makefile
Okay, I will reimplement it now.

2017-01-25 22:58 UTC, iramykytyn commented on demo/Makefile
> +INCLUDE = -I../include -L../bin -I../externals/CXSparse/Include -I../externals/OpenBLAS
removed

2017-01-25 23:08 UTC, iramykytyn commented on src/tests/Makefile
done!

2017-01-25 23:10 UTC, iramykytyn commented on demo/Makefile
> +LDLIBS = -L../bin -lfastfm -L../externals/CXSparse/Lib -lcxsparse -L../externals/OpenBLAS -lopenblas -lpthread -lm
done

2017-01-25 23:13 UTC, iramykytyn commented on src/Makefile
> +LDLIBS = -L../bin -lfastfm -lpthread -lm
changed

2017-01-25 23:18 UTC, iramykytyn commented on demo/Makefile
> +LDLIBS = -L../bin -lfastfm -lopenblas -lpthread -lm
-lopenblas was added mistakenly. Add -lthread was a solution to make it build on your test machines (on mines it is building without it).  Some open blas references were undefined without it. I need more time to investigate how exactly does it affect openblas.

2017-01-26 06:27 UTC, ibayer approved these changes
I still don't understand why we have to link against `-lpthread` in `demo/Makefile`.

2017-01-26 07:05 UTC, merged